/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhosRouteImport } from './routes/trabalhos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrabalhosIdRouteImport } from './routes/trabalhos_.$id'

const TrabalhosRoute = TrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhosIdRoute = TrabalhosIdRouteImport.update({
  id: '/trabalhos_/$id',
  path: '/trabalhos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/trabalhos': typeof TrabalhosRoute
  '/trabalhos/$id': typeof TrabalhosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/trabalhos': typeof TrabalhosRoute
  '/trabalhos/$id': typeof TrabalhosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/trabalhos': typeof TrabalhosRoute
  '/trabalhos_/$id': typeof TrabalhosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/trabalhos'
    | '/trabalhos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/trabalhos'
    | '/trabalhos/$id'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/trabalhos'
    | '/trabalhos_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  TrabalhosRoute: typeof TrabalhosRoute
  TrabalhosIdRoute: typeof TrabalhosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhos': {
      id: '/trabalhos'
      path: '/trabalhos'
      fullPath: '/trabalhos'
      preLoaderRoute: typeof TrabalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhos_/$id': {
      id: '/trabalhos_/$id'
      path: '/trabalhos/$id'
      fullPath: '/trabalhos/$id'
      preLoaderRoute: typeof TrabalhosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  TrabalhosRoute: TrabalhosRoute,
  TrabalhosIdRoute: TrabalhosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
